// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in meter.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkMeter } from '@ngxsmk/core/meter';

describe('meter conformance', () => {
  it('NgxsmkMeter mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkMeter);
  });
});
