// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in pagination.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPagination } from '@ngxsmk/core/pagination';

describe('pagination conformance', () => {
  it('NgxsmkPagination mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPagination);
  });
});
