// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in divider.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkDivider } from '@ngxsmk/core/divider';

describe('divider conformance', () => {
  it('NgxsmkDivider mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkDivider);
  });
});
