// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tree-view.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTreeView } from '@ngxsmk/core/tree-view';

describe('tree-view conformance', () => {
  it('NgxsmkTreeView mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTreeView);
  });
});
