// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in filter-builder.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkFilterBuilder } from '@ngxsmk/core/filter-builder';

describe('filter-builder conformance', () => {
  it('NgxsmkFilterBuilder mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkFilterBuilder);
  });
});
