// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-line.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkLineChart } from '@ngxsmk/core/chart-line';

describe('chart-line conformance', () => {
  it('NgxsmkLineChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkLineChart);
  });
});
