// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in layout.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkLayout } from '@ngxsmk/core/layout';

describe('layout conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkLayout mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkLayout);
  });
});
