// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in form-layout.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkFormLayout } from '@ngxsmk/core/form-layout';

describe('form-layout conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkFormLayout mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkFormLayout);
  });
});
