// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-layout-scroll-button.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatLayoutScrollButton } from '@ngxsmk/core/chat-layout-scroll-button';

describe('chat-layout-scroll-button conformance', () => {
  it('NgxsmkChatLayoutScrollButton mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatLayoutScrollButton);
  });
});
