// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in diff-viewer.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkDiffViewer } from '@ngxsmk/core/diff-viewer';

describe('diff-viewer conformance', () => {
  it('NgxsmkDiffViewer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkDiffViewer);
  });
});
