// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in input-group.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkInputGroup } from '@ngxsmk/core/input-group';

describe('input-group conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkInputGroup mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkInputGroup);
  });
});
