// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in rating.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkRating } from '@ngxsmk/core/rating';

describe('rating conformance', () => {
  it('NgxsmkRating mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkRating);
  });
});
