// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in number-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkNumberInput } from '@ngxsmk/core/number-input';

describe('number-input conformance', () => {
  // KNOWN DEFECT: inner <input> has no label and no ariaLabel input (the +/- buttons do).
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkNumberInput is accessible', async () => {
    await expectConformance(NgxsmkNumberInput);
  });
});
