// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in prompt-carousel.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPromptCarousel } from '@ngxsmk/core/prompt-carousel';

describe('prompt-carousel conformance', () => {
  it('NgxsmkPromptCarousel mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPromptCarousel);
  });
});
