// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in streaming-text.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkStreamingText } from '@ngxsmk/core/streaming-text';

describe('streaming-text conformance', () => {
  it('NgxsmkStreamingText mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkStreamingText);
  });
});
