// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-system-message.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatSystemMessage } from '@ngxsmk/core/chat-system-message';

describe('chat-system-message conformance', () => {
  it('NgxsmkChatSystemMessage mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatSystemMessage);
  });
});
