// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in alert-dialog.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAlertDialog } from '@ngxsmk/core/alert-dialog';

describe('alert-dialog conformance', () => {
  it('NgxsmkAlertDialog mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAlertDialog);
  });
});
