// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in thumbnail.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkThumbnail } from '@ngxsmk/core/thumbnail';

describe('thumbnail conformance', () => {
  // named via the `alt` input, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkThumbnail mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkThumbnail);
  });
});
