// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in code-block.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkCodeBlock } from '@ngxsmk/core/code-block';

describe('code-block conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCodeBlock mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCodeBlock);
  });
});
