// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in h-stack.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkHStack, NgxsmkVStack } from '@ngxsmk/core/h-stack';

describe('h-stack conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkHStack mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkHStack);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkVStack mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkVStack);
  });
});
