// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in carousel.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkCarousel, NgxsmkCarouselSlide } from '@ngxsmk/core/carousel';

describe('carousel conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCarouselSlide mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCarouselSlide);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCarousel mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCarousel);
  });
});
