// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-heatmap.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkHeatmapChart } from '@ngxsmk/core/chart-heatmap';

describe('chart-heatmap conformance', () => {
  it('NgxsmkHeatmapChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkHeatmapChart);
  });
});
