// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in date-range-picker.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkDateRangePicker } from '@ngxsmk/core/date-range-picker';

describe('date-range-picker conformance', () => {
  it('NgxsmkDateRangePicker mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkDateRangePicker);
  });
});
