// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in timeline.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkTimeline, NgxsmkTimelineItem } from '@ngxsmk/core/timeline';

describe('timeline conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTimeline mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTimeline);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTimelineItem mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTimelineItem);
  });
});
