// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in app-shell.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkAppShell } from '@ngxsmk/core/app-shell';

describe('app-shell conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkAppShell mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkAppShell);
  });
});
