// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in citation-viewer.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkCitationViewer } from '@ngxsmk/core/citation-viewer';

describe('citation-viewer conformance', () => {
  it('NgxsmkCitationViewer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkCitationViewer);
  });
});
