// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in top-nav.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import {
  NgxsmkTopNav,
  NgxsmkTopNavHeading,
  NgxsmkTopNavItem,
  NgxsmkTopNavMegaMenu,
  NgxsmkTopNavMegaMenuFeaturedCard,
  NgxsmkTopNavMenu,
} from '@ngxsmk/core/top-nav';

describe('top-nav conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNav mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNav);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNavHeading mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNavHeading);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNavItem mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNavItem);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNavMenu mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNavMenu);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNavMegaMenu mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNavMegaMenu);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTopNavMegaMenuFeaturedCard mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTopNavMegaMenuFeaturedCard);
  });
});
