// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in side-nav.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import {
  NgxsmkSideNav,
  NgxsmkSideNavHeading,
  NgxsmkSideNavItem,
  NgxsmkSideNavSection,
} from '@ngxsmk/core/side-nav';

describe('side-nav conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSideNav mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSideNav);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSideNavHeading mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSideNavHeading);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSideNavItem mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSideNavItem);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSideNavSection mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSideNavSection);
  });
});
