// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in stepper.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkStepper } from '@ngxsmk/core/stepper';

describe('stepper conformance', () => {
  it('NgxsmkStepper mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkStepper);
  });
});
