// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tab-menu.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkTabMenu } from '@ngxsmk/core/tab-menu';

describe('tab-menu conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTabMenu mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTabMenu);
  });
});
