// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-dashboard.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkChartDashboard } from '@ngxsmk/core/chart-dashboard';

describe('chart-dashboard conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkChartDashboard mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkChartDashboard);
  });
});
