// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in status-dot.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkStatusDot } from '@ngxsmk/core/status-dot';

describe('status-dot conformance', () => {
  it('NgxsmkStatusDot mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkStatusDot);
  });
});
