// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tree-select.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTreeSelect } from '@ngxsmk/core/tree-select';

describe('tree-select conformance', () => {
  it('NgxsmkTreeSelect mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTreeSelect);
  });
});
