// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in scroll-spy.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkScrollSpy } from '@ngxsmk/core/scroll-spy';

describe('scroll-spy conformance', () => {
  it('NgxsmkScrollSpy mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkScrollSpy);
  });
});
