// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in resize-handle.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkResizeHandle } from '@ngxsmk/core/resize-handle';

describe('resize-handle conformance', () => {
  it('NgxsmkResizeHandle mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkResizeHandle);
  });
});
