// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in nav-icon.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkNavIcon } from '@ngxsmk/core/nav-icon';

describe('nav-icon conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkNavIcon mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkNavIcon);
  });
});
