// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-candlestick.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkCandlestickChart } from '@ngxsmk/core/chart-candlestick';

describe('chart-candlestick conformance', () => {
  it('NgxsmkCandlestickChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkCandlestickChart);
  });
});
