// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in split-button.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkSplitButton } from '@ngxsmk/core/split-button';

describe('split-button conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSplitButton mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSplitButton);
  });
});
