// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in notification-center.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkNotificationCenter } from '@ngxsmk/core/notification-center';

describe('notification-center conformance', () => {
  it('NgxsmkNotificationCenter mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkNotificationCenter);
  });
});
