// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in playground.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkPlayground } from '@ngxsmk/core/playground';

describe('playground conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkPlayground mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkPlayground);
  });
});
