// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-dictation-button.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatDictationButton } from '@ngxsmk/core/chat-dictation-button';

describe('chat-dictation-button conformance', () => {
  it('NgxsmkChatDictationButton mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatDictationButton);
  });
});
