// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in voice-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkVoiceInput } from '@ngxsmk/core/voice-input';

describe('voice-input conformance', () => {
  it('NgxsmkVoiceInput mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkVoiceInput);
  });
});
