// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in ai-thinking-indicator.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAiThinkingIndicator } from '@ngxsmk/core/ai-thinking-indicator';

describe('ai-thinking-indicator conformance', () => {
  it('NgxsmkAiThinkingIndicator mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAiThinkingIndicator);
  });
});
