// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in image-cropper.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkImageCropper } from '@ngxsmk/core/image-cropper';

describe('image-cropper conformance', () => {
  // KNOWN DEFECT: form control with no labelling API.
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkImageCropper is accessible', async () => {
    await expectConformance(NgxsmkImageCropper);
  });
});
