// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in blockquote.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkBlockquote } from '@ngxsmk/core/blockquote';

describe('blockquote conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkBlockquote mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkBlockquote);
  });
});
