// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in kanban-board.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkKanbanBoard } from '@ngxsmk/core/kanban-board';

describe('kanban-board conformance', () => {
  it('NgxsmkKanbanBoard mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkKanbanBoard);
  });
});
