// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in overflow-list.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkOverflowList } from '@ngxsmk/core/overflow-list';

describe('overflow-list conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkOverflowList mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkOverflowList);
  });
});
