// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in file-upload.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkFileUpload } from '@ngxsmk/core/file-upload';

describe('file-upload conformance', () => {
  it('NgxsmkFileUpload mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkFileUpload);
  });
});
