// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tabs.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTabs } from '@ngxsmk/core/tabs';

describe('tabs conformance', () => {
  it('NgxsmkTabs mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTabs);
  });
});
