// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in response-feedback.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkResponseFeedback } from '@ngxsmk/core/response-feedback';

describe('response-feedback conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkResponseFeedback mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkResponseFeedback);
  });
});
