// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in gauge.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkGauge } from '@ngxsmk/core/gauge';

describe('gauge conformance', () => {
  it('NgxsmkGauge mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkGauge);
  });
});
