// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in credit-card-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkCreditCardInput } from '@ngxsmk/core/credit-card-input';

describe('credit-card-input conformance', () => {
  it('NgxsmkCreditCardInput mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkCreditCardInput);
  });
});
