// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in collapsible.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkCollapsible } from '@ngxsmk/core/collapsible';

describe('collapsible conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCollapsible mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCollapsible);
  });
});
