// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in masonry-grid.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkMasonryGrid } from '@ngxsmk/core/masonry-grid';

describe('masonry-grid conformance', () => {
  it('NgxsmkMasonryGrid mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkMasonryGrid);
  });
});
