// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in nav-heading-menu.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkNavHeadingMenu } from '@ngxsmk/core/nav-heading-menu';

describe('nav-heading-menu conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkNavHeadingMenu mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkNavHeadingMenu);
  });
});
