// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in accordion.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkAccordion } from '@ngxsmk/core/accordion';

describe('accordion conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkAccordion mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkAccordion);
  });
});
