// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-tokenized-text.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatTokenizedText } from '@ngxsmk/core/chat-tokenized-text';

describe('chat-tokenized-text conformance', () => {
  it('NgxsmkChatTokenizedText mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatTokenizedText);
  });
});
