// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in empty-state.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkEmptyState } from '@ngxsmk/core/empty-state';

describe('empty-state conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkEmptyState mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkEmptyState);
  });
});
