// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in aspect-ratio.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkAspectRatio } from '@ngxsmk/core/aspect-ratio';

describe('aspect-ratio conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkAspectRatio mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkAspectRatio);
  });
});
