// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in prompt-library.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPromptLibrary } from '@ngxsmk/core/prompt-library';

describe('prompt-library conformance', () => {
  it('NgxsmkPromptLibrary mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPromptLibrary);
  });
});
