// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in token-counter.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTokenCounter } from '@ngxsmk/core/token-counter';

describe('token-counter conformance', () => {
  it('NgxsmkTokenCounter mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTokenCounter);
  });
});
