// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in power-search.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPowerSearch } from '@ngxsmk/core/power-search';

describe('power-search conformance', () => {
  it('NgxsmkPowerSearch mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPowerSearch);
  });
});
