// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in mobile-nav.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance, expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkMobileNav, NgxsmkMobileNavToggle } from '@ngxsmk/core/mobile-nav';

describe('mobile-nav conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkMobileNav mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkMobileNav);
  });

  it('NgxsmkMobileNavToggle mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkMobileNavToggle);
  });
});
