// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in prompt-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPromptInput } from '@ngxsmk/core/prompt-input';

describe('prompt-input conformance', () => {
  // KNOWN DEFECT: internal icon buttons have no aria-label and the caller cannot supply one.
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkPromptInput is accessible', async () => {
    await expectConformance(NgxsmkPromptInput);
  });
});
