// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in rich-text-editor.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkRichTextEditor } from '@ngxsmk/core/rich-text-editor';

describe('rich-text-editor conformance', () => {
  it('NgxsmkRichTextEditor mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkRichTextEditor);
  });
});
