// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in audio-player.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAudioPlayer } from '@ngxsmk/core/audio-player';

describe('audio-player conformance', () => {
  it('NgxsmkAudioPlayer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAudioPlayer);
  });
});
