// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in skeleton.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkSkeleton } from '@ngxsmk/core/skeleton';

describe('skeleton conformance', () => {
  it('NgxsmkSkeleton mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkSkeleton);
  });
});
