// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in transfer.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkTransfer } from '@ngxsmk/core/transfer';

describe('transfer conformance', () => {
  // role="listbox" has no options until `items` are supplied, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkTransfer mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkTransfer);
  });
});
