// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-pie.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPieChart } from '@ngxsmk/core/chart-pie';

describe('chart-pie conformance', () => {
  it('NgxsmkPieChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPieChart);
  });
});
