// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in breadcrumb-item.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkBreadcrumbItem } from '@ngxsmk/core/breadcrumb-item';

describe('breadcrumb-item conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkBreadcrumbItem mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkBreadcrumbItem);
  });
});
