// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in virtual-scroll.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkVirtualScroll } from '@ngxsmk/core/virtual-scroll';

describe('virtual-scroll conformance', () => {
  it('NgxsmkVirtualScroll mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkVirtualScroll);
  });
});
