// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in password-strength-meter.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPasswordStrengthMeter } from '@ngxsmk/core/password-strength-meter';

describe('password-strength-meter conformance', () => {
  it('NgxsmkPasswordStrengthMeter mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPasswordStrengthMeter);
  });
});
