// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in data-table.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkDataTable } from '@ngxsmk/core/data-table';

describe('data-table conformance', () => {
  it('NgxsmkDataTable mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkDataTable);
  });
});
