// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in lazy-load.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkLazyLoad } from '@ngxsmk/core/lazy-load';

describe('lazy-load conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkLazyLoad mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkLazyLoad);
  });
});
