// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in bottom-tab-bar.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkBottomTab, NgxsmkBottomTabBar } from '@ngxsmk/core/bottom-tab-bar';

describe('bottom-tab-bar conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkBottomTabBar mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkBottomTabBar);
  });

  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkBottomTab mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkBottomTab);
  });
});
