// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in avatar-status-dot.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAvatarStatusDot } from '@ngxsmk/core/avatar-status-dot';

describe('avatar-status-dot conformance', () => {
  it('NgxsmkAvatarStatusDot mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAvatarStatusDot);
  });
});
