// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in expanding-arrow-button.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkExpandingArrowButton } from '@ngxsmk/core/expanding-arrow-button';

describe('expanding-arrow-button conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkExpandingArrowButton mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkExpandingArrowButton);
  });
});
