// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in file-tree.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkFileTree } from '@ngxsmk/core/file-tree';

describe('file-tree conformance', () => {
  it('NgxsmkFileTree mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkFileTree);
  });
});
