// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in form-field.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkFormField } from '@ngxsmk/core/form-field';

describe('form-field conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkFormField mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkFormField);
  });
});
