// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-send-button.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatSendButton } from '@ngxsmk/core/chat-send-button';

describe('chat-send-button conformance', () => {
  it('NgxsmkChatSendButton mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatSendButton);
  });
});
