// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in date-picker.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkDatePicker } from '@ngxsmk/core/date-picker';

describe('date-picker conformance', () => {
  // KNOWN DEFECT: form control with no labelling API.
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkDatePicker is accessible', async () => {
    await expectConformance(NgxsmkDatePicker);
  });
});
