// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-composer-token-element.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatComposerTokenElement } from '@ngxsmk/core/chat-composer-token-element';

describe('chat-composer-token-element conformance', () => {
  it('NgxsmkChatComposerTokenElement mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatComposerTokenElement);
  });
});
