// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-area.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAreaChart } from '@ngxsmk/core/chart-area';

describe('chart-area conformance', () => {
  it('NgxsmkAreaChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAreaChart);
  });
});
