// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tokenizer.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTokenizer } from '@ngxsmk/core/tokenizer';

describe('tokenizer conformance', () => {
  it('NgxsmkTokenizer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTokenizer);
  });
});
