// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in spreadsheet.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkSpreadsheet } from '@ngxsmk/core/spreadsheet';

describe('spreadsheet conformance', () => {
  // role="grid" has no rows until `data` is supplied, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSpreadsheet mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSpreadsheet);
  });
});
