// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in spacer.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkSpacer } from '@ngxsmk/core/spacer';

describe('spacer conformance', () => {
  it('NgxsmkSpacer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkSpacer);
  });
});
