// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in command-palette.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkCommandPalette } from '@ngxsmk/core/command-palette';

describe('command-palette conformance', () => {
  it('NgxsmkCommandPalette mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkCommandPalette);
  });
});
