// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in stat.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkStat } from '@ngxsmk/core/stat';

describe('stat conformance', () => {
  it('NgxsmkStat mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkStat);
  });
});
