// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-message-bubble.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkChatMessageBubble } from '@ngxsmk/core/chat-message-bubble';

describe('chat-message-bubble conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkChatMessageBubble mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkChatMessageBubble);
  });
});
