// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in ai-chat.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAiChat } from '@ngxsmk/core/ai-chat';

describe('ai-chat conformance', () => {
  // KNOWN DEFECT: internal icon buttons have no aria-label and the caller cannot supply one.
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkAiChat is accessible', async () => {
    await expectConformance(NgxsmkAiChat);
  });
});
