// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in toggle-button-group.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkToggleButtonGroup } from '@ngxsmk/core/toggle-button-group';

describe('toggle-button-group conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkToggleButtonGroup mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkToggleButtonGroup);
  });
});
