// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in tour.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTour } from '@ngxsmk/core/tour';

describe('tour conformance', () => {
  it('NgxsmkTour mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTour);
  });
});
