// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in stat-trend-card.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkStatTrendCard } from '@ngxsmk/core/stat-trend-card';

describe('stat-trend-card conformance', () => {
  it('NgxsmkStatTrendCard mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkStatTrendCard);
  });
});
