// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in spinner.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkSpinner } from '@ngxsmk/core/spinner';

describe('spinner conformance', () => {
  it('NgxsmkSpinner mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkSpinner);
  });
});
