// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in timeline-stepper.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTimelineStepper } from '@ngxsmk/core/timeline-stepper';

describe('timeline-stepper conformance', () => {
  it('NgxsmkTimelineStepper mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTimelineStepper);
  });
});
