// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-scatter.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkScatterChart } from '@ngxsmk/core/chart-scatter';

describe('chart-scatter conformance', () => {
  it('NgxsmkScatterChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkScatterChart);
  });
});
