// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in calendar-heatmap.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkCalendarHeatmap } from '@ngxsmk/core/calendar-heatmap';

describe('calendar-heatmap conformance', () => {
  // role="grid" has no cells until `values` are supplied, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCalendarHeatmap mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCalendarHeatmap);
  });
});
