// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in time-picker.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkTimePicker } from '@ngxsmk/core/time-picker';

describe('time-picker conformance', () => {
  it('NgxsmkTimePicker mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkTimePicker);
  });
});
