// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in checkbox.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkCheckbox } from '@ngxsmk/core/checkbox';

describe('checkbox conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkCheckbox mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkCheckbox);
  });
});
