// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in audio-visualizer.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkAudioVisualizer } from '@ngxsmk/core/audio-visualizer';

describe('audio-visualizer conformance', () => {
  it('NgxsmkAudioVisualizer mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkAudioVisualizer);
  });
});
