// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in avatar.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkAvatar } from '@ngxsmk/core/avatar';

describe('avatar conformance', () => {
  // named via the `name` input, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkAvatar mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkAvatar);
  });
});
