// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chart-bar.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkBarChart } from '@ngxsmk/core/chart-bar';

describe('chart-bar conformance', () => {
  it('NgxsmkBarChart mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkBarChart);
  });
});
