// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in switch.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkSwitch } from '@ngxsmk/core/switch';

describe('switch conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSwitch mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSwitch);
  });
});
