// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-message-metadata.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkChatMessageMetadata } from '@ngxsmk/core/chat-message-metadata';

describe('chat-message-metadata conformance', () => {
  it('NgxsmkChatMessageMetadata mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkChatMessageMetadata);
  });
});
