// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in progress-circle.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkProgressCircle } from '@ngxsmk/core/progress-circle';

describe('progress-circle conformance', () => {
  // KNOWN DEFECT: role="progressbar" with no accessible name and no input to set one.
  // Asserted as a failure so the suite stays green while the defect stays
  // visible; this test will start failing once the component is fixed, which
  // is the signal to drop it from KNOWN_A11Y_BUGS in the generator.
  it.fails('NgxsmkProgressCircle is accessible', async () => {
    await expectConformance(NgxsmkProgressCircle);
  });
});
