// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in otp-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkOtpInput } from '@ngxsmk/core/otp-input';

describe('otp-input conformance', () => {
  it('NgxsmkOtpInput mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkOtpInput);
  });
});
