// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in slider.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkSlider } from '@ngxsmk/core/slider';

describe('slider conformance', () => {
  // named via the `ariaLabel` input, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkSlider mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkSlider);
  });
});
