// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in chat-input.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkChatInput } from '@ngxsmk/core/chat-input';

describe('chat-input conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkChatInput mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkChatInput);
  });
});
