// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in compare-image.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkCompareImage } from '@ngxsmk/core/compare-image';

describe('compare-image conformance', () => {
  it('NgxsmkCompareImage mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkCompareImage);
  });
});
