// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in pin-input.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkPinInput } from '@ngxsmk/core/pin-input';

describe('pin-input conformance', () => {
  it('NgxsmkPinInput mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkPinInput);
  });
});
