// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in range-slider.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkRangeSlider } from '@ngxsmk/core/range-slider';

describe('range-slider conformance', () => {
  it('NgxsmkRangeSlider mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkRangeSlider);
  });
});
