// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in hover-card.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkHoverCard } from '@ngxsmk/core/hover-card';

describe('hover-card conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkHoverCard mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkHoverCard);
  });
});
