// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in progress.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkProgress } from '@ngxsmk/core/progress';

describe('progress conformance', () => {
  it('NgxsmkProgress mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkProgress);
  });
});
