// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in markdown-viewer.spec.ts.
import { describe, it } from 'vitest';
import { expectMountsCleanly } from '@ngxsmk/cdk/testing';
import { NgxsmkMarkdownViewer } from '@ngxsmk/core/markdown-viewer';

describe('markdown-viewer conformance', () => {
  // Projects content — its accessible name comes from the caller, so the
  // axe audit belongs in a test that supplies it.
  it('NgxsmkMarkdownViewer mounts cleanly', async () => {
    await expectMountsCleanly(NgxsmkMarkdownViewer);
  });
});
