// GENERATED by tools/scripts/generate-conformance-specs.mjs — do not edit.
// Baseline conformance only. Add behavior tests in color-picker.spec.ts.
import { describe, it } from 'vitest';
import { expectConformance } from '@ngxsmk/cdk/testing';
import { NgxsmkColorPicker } from '@ngxsmk/core/color-picker';

describe('color-picker conformance', () => {
  it('NgxsmkColorPicker mounts cleanly and is accessible', async () => {
    await expectConformance(NgxsmkColorPicker);
  });
});
